### PR TITLE
Fix #1471 - Add remote build submission metrics such as upload time

### LINKED ISSUE #1471: Add metrics for remote build service.
In the submission response when submitting to Streaming Analytics, seems we could include some metrics to help any future diagnostics:

- Size of the build archive
- Upload time
- Time wating for build, broken into states, e.g. timeQueued, timeBuilding, etc.
- Time to submit

Adding something like this to the returned JSON object:
```
"metrics": {
   "codeArchiveSize": 234433,
   "uploadTime": 23.3,
   "queueTime": 0,
   "buildTime": 12.1,
   "submissionTime": 3.0
}
```

### PR DESCRIPTION
**Pull request by ddebrunner**
See #1471

### CODE REVIEW

File: java/src/com/ibm/streamsx/rest/AbstractStreamingAnalyticsService.java [hunk 1]
```diff
@@ -170,10 +170,17 @@ protected void setAuthorization(String authorization) {
...
+        return "buildState_" + state + "Time_ms";
+    }
+    
     @Override
     public Result<Job, JsonObject> buildAndSubmitJob(File archive, JsonObject jco,
             String buildName) throws IOException {
-    	
+        
+        JsonObject metrics = new JsonObject();
+        metrics.addProperty("buildArchiveSize", archive.length());
```
Comment (wmarshall484) [inline java/src/com/ibm/streamsx/rest/AbstractStreamingAnalyticsService.java]: It might be nice to have an interface with the properties of the metrics object so we can keep track of what gets set where.

**Comment by ddebrunner** [comment]
Moved keys to an existing interface.
